name: otlplus
description: Online Timeplanner with Lectures Plus App @ KAIST

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.7+17

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.4
  dotted_border: ^2.0.0+2
  flutter_inappwebview: ^5.3.2 # No desktop support
  flutter_web_browser: ^0.16.0 # No desktop support
  intl: ^0.17.0
  multi_select_flutter: ^4.0.0
  open_file: ^3.2.1 # No desktop support
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  provider: ^6.0.2
  url_launcher: ^6.0.17
  equatable: ^2.0.3
  shared_preferences: ^2.0.11
  flutter_platform_widgets: ^1.12.1
  cupertino_icons: ^1.0.4
  # Firebase
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_crashlytics: ^2.5.3

dev_dependencies:
  test: ^1.17.12
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon-512.png"
  adaptive_icon_background: "#F9F0F0"
  adaptive_icon_foreground: "assets/icon-512-foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/bg.4556cdee.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
