// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZlFDx8QSwvxQQZCr7Y7Cs4-WnRKAayvI',
    appId: '1:446589104698:android:a2e2207ea2f54bd830bb03',
    messagingSenderId: '446589104698',
    projectId: 'otl-plus-app',
    storageBucket: 'otl-plus-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6GAdd5I0oaK3ahdjTfRjj6NHPcvfWB4Q',
    appId: '1:446589104698:ios:3c3b9fad7dcbcbb830bb03',
    messagingSenderId: '446589104698',
    projectId: 'otl-plus-app',
    storageBucket: 'otl-plus-app.appspot.com',
    iosClientId: '446589104698-779q1t4sght9akffsomaub8rut3skl4r.apps.googleusercontent.com',
    iosBundleId: 'org.sparcs.otlplus',
  );
}
