update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Set timestamp version from pubspec.yaml"
  lane :set_timestamp_version do
      yaml_file_path = "../../pubspec.yaml"
      data = YAML.load_file(yaml_file_path)
      version = data["version"]

      version_number = data["version"].split("+")[0]
      version_code = Time.now.strftime("%y%m%d%H%M").to_i - 2100000000
      new_version = "#{version_number}+#{version_code}"

      data["version"] = new_version
      File.open(yaml_file_path, 'w') { |f| YAML.dump(data, f) }
  end

  desc "Deploy a alpha version to the Google Play"
  lane :alpha do
    set_timestamp_version
    sh "flutter build appbundle"
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "alpha",
    )
  end
end
