name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION: '3.0.5'
  JAVA_VERSION: '11'

jobs:
  build-android:
    name: Build Android
    runs-on: macOS
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Create key.properties
        run: |
          echo "storeFile=../ci.jks" > android/key.properties
          echo "storePassword=123456" >> android/key.properties
          echo "keyPassword=123456" >> android/key.properties
          echo "keyAlias=ci" >> android/key.properties   
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release

  build-ios:
    name: Build iOS
    runs-on: macOS
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --release --no-codesign
