name: Coverage

on: [push]

env:
  FLUTTER_VERSION: "3.24.0"

jobs:
  coverage:
    name: Upload coverage to Codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Install lcov
        run: sudo apt-get install -y lcov
      - name: Install dependencies
        run: flutter pub get
      - name: Test
        run: ./test/run.sh
      - name: Upload
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
