name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FLUTTER_VERSION: "3.22.3"

jobs:
  lint:
    name: Format and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Format
        run: dart format . --set-exit-if-changed
      - name: Analyze
        run: flutter analyze
