name: Release Drafter

on:
  push:
    branches: [ main ]

jobs:
  update-release-draft:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.TAG_PAT }}
