name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    name: Unit & Widget Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'
      - name: Install lcov
        run: sudo apt-get install -y lcov
      - name: Install dependencies
        run: flutter pub get
      - name: Test
        run: sh ./test/run.sh

  integration-android:
    name: Integration Test on Android
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'
      - name: Test on Android
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: 28
          script: flutter drive --target=test_driver/app.dart

  integration-ios:
    name: Integration Test on iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'
      - name: Start Simulator
        run: |
          xcrun xctrace list devices | awk '/iPhone 12 Pro/{print $6}' | tr -d '()' | read UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - name: Test on iOS
        run: "flutter drive --target=test_driver/app.dart"