name: Test

on:
  push:
    branches: [ main ]

env:
  FLUTTER_VERSION: '3.7'
  JAVA_VERSION: '11'

jobs:
  unit:
    name: Unit & Widget Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Install dependencies
        run: flutter pub get
      - name: Test
        run: flutter test

  integration-android:
    name: Integration Test on Android
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Test on Android
        uses: reactivecircus/android-emulator-runner@v2.19.1
        with:
          api-level: 28
          script: flutter drive -d emulator-5554 --target=test_driver/app.dart

  integration-ios:
    name: Integration Test on iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: List Simulator
        run: echo "UDID=$(xcrun xctrace list devices 2>&1 | awk '/iPhone 14 Pro/ {print $NF; exit}' | tr -d '()')" >> $GITHUB_ENV
      - name: Start Simulator
        run: xcrun simctl boot ${{ env.UDID }}
      - name: Test on iOS
        run: "flutter drive --target=test_driver/app.dart"
      - name: Quit iOS Simulators
        run: xcrun simctl shutdown all
